name = "fun-trivia-game"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./dist" }

routes = [
  { pattern = "trivia.emilycogsdill.com", custom_domain = true }
]

[vars]
CF_ACCESS_TEAM_DOMAIN = "https://emilycogsdill.cloudflareaccess.com"
CF_ACCESS_AUD = "77c6b019856fd2f0fbffbd3499772a5019c6dc5f9260fc57e09bd0837e006acf"

[[d1_databases]]
binding = "DB"
database_name = "trivia-trainer"
database_id = "f647046c-e114-41ca-9231-7942bdfb8b82"
