name = "fun-trivia-game"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./dist" }

routes = [
  { pattern = "trivia.emilycogsdill.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "trivia-trainer"
database_id = "f647046c-e114-41ca-9231-7942bdfb8b82"
